/*
  Warnings:

  - The values [CONSULTATION_CARDIOLOGY,CONSULTATION_DERMATOLOGY,CONSULTATION_ENDOCRINOLOGY,CONSULTATION_ENT,CONSULTATION_GASTROENTEROLOGY,CONSULTATION_NEUROLOGY,CONSULTATION_OB_GYNE,CONSULTATION_ONCOLOGY,CONSULTATION_OPHTHALMOLOGY,CONSULTATION_ORTHOPEDICS,CONSULTATION_PEDIATRICS,CONSULTATION_PSYCHIATRY,CONSULTATION_PULMONOLOGY,CONSULTATION_REHABILITATION,CONSULTATION_RHEUMATOLOGY,CONSULTATION_UROLOGY,BLOOD_CHEMISTRY_BUN,BLOOD_CHEMISTRY_CREATININE,BLOOD_CHEMISTRY_FBS,BLOOD_CHEMISTRY_RBS,BLOOD_CHEMISTRY_CHOLESTEROL,BLOOD_CHEMISTRY_TRIGLYCERIDES,BLOOD_CHEMISTRY_HDL,BLOOD_CHEMISTRY_LDL,BLOOD_CHEMISTRY_AST,BLOOD_CHEMISTRY_ALT,BLOOD_CHEMISTRY_LDH,BLOOD_CHEMISTRY_ELECTROLYTES,HEMATOLOGY_HEMOGLOBIN,HEMATOLOGY_HEMATOCRIT,HEMATOLOGY_PLATELET_COUNT,HEMATOLOGY_COAGULATION,HEMATOLOGY_CT_BT,HEMATOLOGY_PERIPHERAL_SMEAR,CLINICAL_OCCULT_BLOOD,CLINICAL_SEMEN_ANALYSIS,CLINICAL_BODY_FLUID_ANALYSIS,CLINICAL_PREGNANCY_TEST,BACTERIOLOGY_SPUTUM,BACTERIOLOGY_GRAM_STAIN,BACTERIOLOGY_CULTURE_SENS,BACTERIOLOGY_THROAT_SWAB,BACTERIOLOGY_BLOOD_CULTURE,BACTERIOLOGY_URINE_CULTURE,HISTOPATHOLOGY_PAPS,HISTOPATHOLOGY_BIOPSY,HISTOPATHOLOGY_CYTOLOGY,X_RAY_CHEST_AP_LAT,X_RAY_SKULL_AP_LAT,X_RAY_THORACIC_CAGE,X_RAY_SHOULDER,X_RAY_CLAVICLE,X_RAY_ARM_AP_LAT,X_RAY_HAND,X_RAY_FOOT,ULTRASOUND_WHOLE_ABD,ULTRASOUND_PELVIC,ULTRASOUND_TRANSVAGINAL,ULTRASOUND_THYROID,ULTRASOUND_BREAST,ULTRASOUND_KUB,ULTRASOUND_OB,ULTRASOUND_OB_NO_READING,ULTRASOUND_DOPPLER,ULTRASOUND_SCROTAL,ULTRASOUND_PROSTATE,CT_SCAN_BRAIN_STROKE,CT_SCAN_SINUSES,CT_SCAN_ANGIOGRAM_HEAD,CT_SCAN_ANGIOGRAM_NECK,CT_SCAN_CHEST,CT_SCAN_CHEST_HRCT,CT_SCAN_CHEST_PULMO_EMB,CT_SCAN_ANGIOGRAM_CORONARY,CT_SCAN_ABD,CT_SCAN_ABD_PELVIS,CT_SCAN_KUB,CT_SCAN_ANGIOGRAM_ABD,CT_SCAN_JOINT,MRI_C_SPINE,MRI_T_SPINE,MRI_L_SPINE,MAMMOGRAPHY_BILATERAL,MAMMOGRAPHY_UNILATERAL,OPTICAL_REFRACTION,OPTICAL_TONOMETRY,OPTICAL_CHALAZION_REMOVAL,OPTICAL_FOREIGN_BODY_REMOVAL,OPTICAL_OCT_OPTIC_NERVE,OPTICAL_OCT_MACULA,HEARING_AUDIOMETRY,HEARING_TYMPANOMETRY,ENT_EAR_IRRIGATION,ENT_EAR_WAX_REMOVAL,ENT_NASAL_ENDOSCOPY,ENT_LARYNGOSCOPY,ENT_VIDEOSTROBOSCOPY,DENTAL_EXTRACTION,DENTAL_FILLING_TEMPORARY,DENTAL_FILLING_PERMANENT,DENTAL_ROOT_CANAL,DENTAL_CROWN_PLACEMENT,DENTAL_BRIDGE_PLACEMENT,DENTAL_WHITENING,THERAPY_OCCUPATIONAL,THERAPY_SPEECH,THERAPY_RESPIRATORY,THERAPY_VESTIBULAR,THERAPY_CARDIAC,THERAPY_LYMPHEDEMA,THERAPY_NEUROLOGICAL,ONCOLOGY_RADIATION_THERAPY,ONCOLOGY_PALLIATIVE_CARE,ONCOLOGY_HORMONAL_THERAPY,ONCOLOGY_IMMUNOTHERAPY,ONCOLOGY_TARGETED_THERAPY,PROCEDURE_CAUTERIZATION,PROCEDURE_CIRCUMCISION,PROCEDURE_DEBRIDEMENT,PROCEDURE_DRESSING,PROCEDURE_EAR_PIERCING,PROCEDURE_INCISION,PROCEDURE_DRAINAGE,PROCEDURE_WOUND_SUTURING,PROCEDURE_WOUND_SUTURE_REMOVAL,PROCEDURE_CYST_REMOVAL,PROCEDURE_LIPOMA_REMOVAL,PROCEDURE_SKIN_TAG_REMOVAL,PROCEDURE_NAIL_REMOVAL,PROCEDURE_WART_REMOVAL,PROCEDURE_BIOPSY,PROCEDURE_PFT,PROCEDURE_LUMBAR_TAP,PROCEDURE_PARACENTESIS,PROCEDURE_UMBILICAL_CATH,PROCEDURE_BRONCHOSCOPY,PROCEDURE_THORACENTESIS,VACCINATION_HEPATITIS_A,VACCINATION_HEPATITIS_B,VACCINATION_HPV,VACCINATION_INFLUENZA,VACCINATION_MMR,VACCINATION_POLIO,VACCINATION_RABIES,VACCINATION_ROTAVIRUS,VACCINATION_PNEUMOCOCCAL,VACCINATION_MENINGOCOCCAL,VACCINATION_TDAP] on the enum `ServiceType` will be removed. If these variants are still used in the database, this will fail.
  - The primary key for the `Address` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to drop the column `addressID` on the `Address` table. All the data in the column will be lost.
  - Added the required column `updatedAt` to the `Admin` table without a default value. This is not possible if the table is not empty.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ServiceType_new" AS ENUM ('CONSULTATION_GENERAL', 'BLOOD_CHEMISTRY_BUA', 'HEMATOLOGY_CBC', 'CLINICAL_FECALYSIS', 'CLINICAL_URINALYSIS', 'X_RAY_CHEST_PA', 'X_RAY_C_SPINE', 'X_RAY_T_SPINE', 'X_RAY_L_SPINE', 'ULTRASOUND_ABDOMINAL', 'CT_SCAN_HEAD', 'CT_SCAN_C_SPINE', 'CT_SCAN_T_SPINE', 'CT_SCAN_L_SPINE', 'MRI_BRAIN', 'DENTAL_SCALING', 'THERAPY_PHYSICAL', 'ONCOLOGY_CHEMOTHERAPY', 'PROCEDURE_EEG', 'PROCEDURE_ECG', 'PROCEDURE_DIALYSIS', 'PROCEDURE_COLONOSCOPY', 'PROCEDURE_GASTROSCOPY', 'PROCEDURE_LABOR_DELIVERY', 'VACCINATION_COVID19');
ALTER TABLE "OutpatientService" ALTER COLUMN "serviceType" TYPE "ServiceType_new" USING ("serviceType"::text::"ServiceType_new");
ALTER TYPE "ServiceType" RENAME TO "ServiceType_old";
ALTER TYPE "ServiceType_new" RENAME TO "ServiceType";
DROP TYPE "ServiceType_old";
COMMIT;

-- DropIndex
DROP INDEX "Address_facilityID_key";

-- DropIndex
DROP INDEX "Region_regionID_key";

-- AlterTable
ALTER TABLE "Address" DROP CONSTRAINT "Address_pkey",
DROP COLUMN "addressID",
ADD CONSTRAINT "Address_pkey" PRIMARY KEY ("facilityID");

-- AlterTable
ALTER TABLE "Admin" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL;

-- AlterTable
ALTER TABLE "ICUService" ALTER COLUMN "load" SET DEFAULT 'CLOSED';
